services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - ${DEV_PORT}:5173
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development