services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    volumes:
      - frontend-build:/app/dist
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:stable-alpine
    ports:
      - ${PORT}:80
    volumes:
      - frontend-build:/usr/share/nginx/html
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

volumes:
  frontend-build: